#based on repo at https://github.com/18F/guides-template/tree/publishing
baseurl: /APIPrototype
markdown: redcarpet
redcarpet:
  extensions: ["autolink", "tables"]
name: My Medication List - Prototype
exclude:
- go
- copy-template
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md

permalink: pretty

# Author/Organization info to be displayed in the templates
author:
  name: Xfinion
  url: http://www.xfinion.com

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
#logourl: /assets/img/18f-logo.png
#logoalt: 18F logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: index.html
  internal: true
- text: About
  url: about/
  internal: true
- text: Methodology
  url: methodology/
  internal: true
- text: Design
  url: design/
  internal: true
- text: Development
  url: development/
  internal: true
- text: Testing
  url: testing/
  internal: true
- text: Deployment
  url: deployment/
  internal: true
- text: Configuration Management
  url: configuration-management/
  internal: true
- text: Continuous Integration
  url: continuous-integration/
  internal: true
  
- text: Continuous Monitoring
  url: continuous-monitoring/
  internal: true  
- text: Security
  url: security/
  internal: true
- text: Miscellaneous
  url: miscellaneous/
  internal: true
- text: RFQ Evidence
  url: rfq-evaluation-criteria-evidence/
  internal: true

repos:
- name: Guides Template
  description: Main repository
  url: https://github.com/goswamivijay/APIPrototype

# Style Variables
brand_color: "#1188ff"

google_analytics_ua: UA-64764688-1
